married(avr,sara).                
married(yit,rivka).
married(yaak,lea).
married(yaak,rachel).
parent(avr,yit).
parent(sara,yit).
parent(rivka,yaak).
parent(yit,yaak).
parent(yaak,reuven). 
parent(yaak,shimon).
parent(yaak,levi).
parent(yaak,yehuda).
parent(yaak,dina).
parent(yaak,yoseph).
parent(yaak,binyamin).
parent(yehuda,zerach).
parent(yehuda,peretz).
parent(levi,kehat).
parent(levi,gershon).
parent(levi,merari).
parent(lea,reuven).  
parent(lea,shimon).
parent(lea,levi).
parent(lea,yehuda).
parent(lea,dina).
parent(rachel,yoseph).
parent(rachel,binyamin).
male(avr).
male(yit).
male(yaak).
male(reuven).
male(shimon).
male(levi).
male(yehuda).
male(yoseph).
male(binyamin).
male(zerach).
male(peretz).
male(kehat).
male(gershon).
male(merari).
male(reuven).
male(shimon).
female(sara).
female(rivka).
female(lea).
female(rachel).
female(dina).